name: CI

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['main']
  merge_group:

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (with cache)
        run: npm install

      - run: cp .env.example .env.local

      - name: Build
        run: npm run build

      - name: Check formatting
        run: npm run format
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (with cache)
        run: npm install

      - run: cp .env.example .env.local

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint:repo
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (with cache)
        run: npm run install

      - run: cp .env.example .env.local

      - name: Build
        run: npm run build

      - name: Typecheck
        run: npm run typecheck
